description: Example barbari configuration
alignment_holes:
  hole_size: 3.4
  hole_offset: 1
  tool_size: 1.5
  cut_z: -10
  travel_z: 2
  feed_rate: 100
  spindle_speed: 12000
  multi_depth: true
  depth_per_pass: 0.2
isolation_routing:
  tool_size: 0.18
  width: 1
  passes: 2
  pass_overlap: 1
  cut_z: -0.2
  travel_z: 2
  feed_rate: 200
  spindle_speed: 12000
  multi_depth: true
  depth_per_pass: 0.1
drill:
  via:
    max_size: 0.4
    specs:
      - type: cnc_drill
        params:
          tool_size: 0.4
          drill_z: -2.5
          travel_z: 2
          feed_rate: 50
          spindle_speed: 12000
  drilled:
    min_size: 0.4
    max_size: 1.0
    specs:
      - type: cnc_drill
        params:
          tool_size: 1.0
          drill_z: -2.5
          travel_z: 2
          feed_rate: 50
          spindle_speed: 12000
  milled:
    min_size: 1.0
    specs:
      - type: mill_holes
        params:
          tool_size: 1
          cut_z: -2.5
          travel_z: 2
          feed_rate: 100
          spindle_speed: 12000
          multi_depth: true
          depth_per_pass: 0.2
slot:
  large:
    min_size: 1.0
    specs:
      - type: mill_slots
        params:
          tool_size: 1
          cut_z: -2.5
          travel_z: 2
          feed_rate: 100
          spindle_speed: 12000
          multi_depth: true
          depth_per_pass: 0.2
edge_cuts:
  tool_size: 1.5
  margin: 0
  gap_size: 1
  gaps: lr
  cut_z: -2.5
  travel_z: 2
  feed_rate: 100
  spindle_speed: 12000
  multi_depth: true
  depth_per_pass: 0.2
